post_install() {
    systemctl enable --now libvirtd.service
    sed -i 's/^#unix_sock_group = "libvirt"/unix_sock_group = "libvirt"/g' /etc/libvirt/libvirtd.conf
    sed -i 's/^#unix_sock_rw_perms = "0770"/unix_sock_rw_perms = "0770"/g' /etc/libvirt/libvirtd.conf
    groupadd libvirt
    groupadd kvm
    for user in $(ls /home) ; do
        usermod -aG libvirt $user
        usermod -aG kvm $user
    done
}

post_upgrade() {
    return 0
}
