FROM alpine

RUN apk --update add nginx

# Configure nginx logs to go to Docker log collection (via stdout/stderr)
RUN ln -s -f /dev/stdout /var/log/nginx/access.log
RUN ln -s -f /dev/stderr /var/log/nginx/error.log

RUN mkdir -p /tmp/nginx
RUN mkdir -p /web/www

ADD nginx.conf /etc/nginx/

EXPOSE 80

CMD exec nginx -g "daemon off;"
